### PR TITLE
Pull in multiple upstream changes

### PR DESCRIPTION
**Pull request by felddy**
Pulls in changes from multiple levels of upstreaminess.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
LGTM ✅

**Review by dav3r — APPROVED** [review]
🐐

**Review by jsf9k — COMMENTED** [review]
These changes all look good to me.  Did I miss anything, or are these _just_ a pull from upstream?  Just want to make sure there weren't any changes-changes that I should be inspecting more closely.

**Review by jsf9k — APPROVED** [review]
Looks like this is just a straight pull from upstream with no other changes.  I'll approve!

**Pull request merged**
